import type {
  DemoContentReport,
  DemoEssayVersion,
  DemoLicense,
  DemoPodcastEpisode,
  DemoQuestionVersion,
} from "./admin-content-types";

export const demoLicenses: DemoLicense[] = [
  {
    key: "demo-internal-license",
    copyrightOwner: "DEMO_NOT_FOR_PUBLICATION Owner",
    expiresAt: new Date("2026-07-15T00:00:00.000Z"),
    status: "ACTIVE",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
  },
];

export const demoQuestions: DemoQuestionVersion[] = [
  {
    id: "demo-question-1",
    subject: "Civil Procedure",
    category: "Jurisdiction and venue",
    examTrack: "LEGACY_UBE",
    format: "SINGLE_SELECT",
    stem: "DEMO_NOT_FOR_PUBLICATION placeholder stem.",
    callOfQuestion: "DEMO_NOT_FOR_PUBLICATION placeholder call.",
    choices: [
      {
        label: "A",
        text: "DEMO_NOT_FOR_PUBLICATION choice A",
        isCorrect: true,
        rationale: "DEMO_NOT_FOR_PUBLICATION rationale A",
        distractorType: "NONE",
      },
      {
        label: "B",
        text: "DEMO_NOT_FOR_PUBLICATION choice B",
        isCorrect: false,
        rationale: "DEMO_NOT_FOR_PUBLICATION rationale B",
        distractorType: "SCOPE_ERROR",
      },
    ],
    primaryTopic: "mbe.category.civil-procedure.jurisdiction-and-venue",
    secondaryTopics: [],
    difficulty: "MEDIUM",
    estimatedSeconds: 90,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-question-missing-rationale",
    subject: "Torts",
    category: "Negligence",
    examTrack: "LEGACY_UBE",
    format: "SINGLE_SELECT",
    stem: "DEMO_NOT_FOR_PUBLICATION placeholder stem.",
    callOfQuestion: "DEMO_NOT_FOR_PUBLICATION placeholder call.",
    choices: [
      {
        label: "A",
        text: "DEMO_NOT_FOR_PUBLICATION choice A",
        isCorrect: true,
        rationale: "DEMO_NOT_FOR_PUBLICATION rationale A",
        distractorType: "NONE",
      },
      {
        label: "B",
        text: "DEMO_NOT_FOR_PUBLICATION choice B",
        isCorrect: false,
        rationale: "",
        distractorType: "NONE",
      },
    ],
    primaryTopic: "mbe.category.torts.negligence",
    secondaryTopics: [],
    difficulty: "EASY",
    estimatedSeconds: 75,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    effectiveFrom: new Date("2026-01-01T00:00:00.000Z"),
    status: "DRAFT",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-01-01T00:00:00.000Z"),
  },
  {
    id: "demo-question-2",
    subject: "Torts",
    category: "Negligence",
    examTrack: "LEGACY_UBE",
    format: "SINGLE_SELECT",
    stem: "DEMO_NOT_FOR_PUBLICATION second placeholder stem.",
    callOfQuestion: "DEMO_NOT_FOR_PUBLICATION second placeholder call.",
    choices: [
      {
        label: "A",
        text: "DEMO_NOT_FOR_PUBLICATION second choice A",
        isCorrect: false,
        rationale: "DEMO_NOT_FOR_PUBLICATION second rationale A",
        distractorType: "FACT_CONFUSION",
      },
      {
        label: "B",
        text: "DEMO_NOT_FOR_PUBLICATION second choice B",
        isCorrect: true,
        rationale: "DEMO_NOT_FOR_PUBLICATION second rationale B",
        distractorType: "NONE",
      },
    ],
    primaryTopic: "mbe.category.torts.negligence",
    secondaryTopics: [],
    difficulty: "EASY",
    estimatedSeconds: 75,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-select-two",
    subject: "NextGen Skills",
    category: "Issue spotting",
    examTrack: "NEXTGEN_UBE",
    format: "SELECT_TWO",
    stem: "DEMO_NOT_FOR_PUBLICATION NextGen select-two placeholder stem.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION select exactly two placeholder responses.",
    choices: [
      {
        label: "A",
        text: "DEMO_NOT_FOR_PUBLICATION select-two choice A",
        isCorrect: true,
        rationale: "DEMO_NOT_FOR_PUBLICATION select-two rationale A",
        distractorType: "NONE",
      },
      {
        label: "B",
        text: "DEMO_NOT_FOR_PUBLICATION select-two choice B",
        isCorrect: true,
        rationale: "DEMO_NOT_FOR_PUBLICATION select-two rationale B",
        distractorType: "NONE",
      },
      {
        label: "C",
        text: "DEMO_NOT_FOR_PUBLICATION select-two choice C",
        isCorrect: false,
        rationale: "DEMO_NOT_FOR_PUBLICATION select-two rationale C",
        distractorType: "FACT_CONFUSION",
      },
    ],
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: [],
    lawyeringSkillTopic: "nextgen.skill.01",
    masteryDimension: "LAWYERING_SKILL",
    difficulty: "MEDIUM",
    estimatedSeconds: 120,
    setLevelTimingSeconds: 120,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-integrated-1",
    subject: "NextGen Skills",
    category: "Client counseling",
    examTrack: "NEXTGEN_UBE",
    format: "INTEGRATED_SET",
    stem: "DEMO_NOT_FOR_PUBLICATION integrated-set prompt placeholder.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION provide two written placeholder responses.",
    choices: [],
    integratedSetId: "demo-nextgen-integrated-set-1",
    commonFactScenario:
      "DEMO_NOT_FOR_PUBLICATION shared fact scenario placeholder for the integrated set.",
    attachedResources: [
      {
        id: "demo-nextgen-resource-1",
        title: "DEMO_NOT_FOR_PUBLICATION legal resource placeholder",
        resourceType: "LEGAL_RESOURCE",
        citationLabel: "DEMO_NOT_FOR_PUBLICATION Resource A",
        content:
          "DEMO_NOT_FOR_PUBLICATION legal resource text placeholder for split-screen reading.",
      },
    ],
    exhibits: [
      {
        id: "demo-nextgen-exhibit-1",
        title: "DEMO_NOT_FOR_PUBLICATION exhibit placeholder",
        resourceType: "EXHIBIT",
        content:
          "DEMO_NOT_FOR_PUBLICATION exhibit text placeholder for integrated practice.",
      },
    ],
    responseAreas: [
      {
        id: "short",
        label: "DEMO_NOT_FOR_PUBLICATION short response",
        responseType: "SHORT_TEXT",
        maxWords: 75,
      },
      {
        id: "medium",
        label: "DEMO_NOT_FOR_PUBLICATION medium response",
        responseType: "MEDIUM_TEXT",
        maxWords: 250,
      },
    ],
    scoringRubric: {
      version: 1,
      maxPoints: 2,
      scale: "NEXTGEN_POINTS",
      items: [
        {
          id: "demo-nextgen-integrated-rubric-short",
          responseAreaId: "short",
          label: "DEMO_NOT_FOR_PUBLICATION short rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION short"],
        },
        {
          id: "demo-nextgen-integrated-rubric-medium",
          responseAreaId: "medium",
          label: "DEMO_NOT_FOR_PUBLICATION medium rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION medium"],
        },
      ],
    },
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: ["nextgen.skill.02"],
    lawyeringSkillTopic: "nextgen.skill.02",
    masteryDimension: "LAWYERING_SKILL",
    difficulty: "MEDIUM",
    estimatedSeconds: 300,
    setLevelTimingSeconds: 600,
    simulationBlueprintKey: "demo-nextgen-july-2026",
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-short-answer",
    subject: "NextGen Skills",
    category: "Short written response",
    examTrack: "NEXTGEN_UBE",
    format: "SHORT_ANSWER",
    stem: "DEMO_NOT_FOR_PUBLICATION short-answer prompt placeholder.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION provide a short placeholder response.",
    choices: [],
    responseAreas: [
      {
        id: "short-answer",
        label: "DEMO_NOT_FOR_PUBLICATION short answer",
        responseType: "SHORT_TEXT",
        maxWords: 75,
      },
    ],
    scoringRubric: {
      version: 1,
      maxPoints: 1,
      scale: "NEXTGEN_POINTS",
      items: [
        {
          id: "demo-nextgen-short-rubric",
          responseAreaId: "short-answer",
          label: "DEMO_NOT_FOR_PUBLICATION short-answer rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION short"],
        },
      ],
    },
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: [],
    lawyeringSkillTopic: "nextgen.skill.01",
    masteryDimension: "DOCTRINAL",
    difficulty: "EASY",
    estimatedSeconds: 120,
    setLevelTimingSeconds: 120,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-medium-answer",
    subject: "NextGen Skills",
    category: "Medium written response",
    examTrack: "NEXTGEN_UBE",
    format: "MEDIUM_ANSWER",
    stem: "DEMO_NOT_FOR_PUBLICATION medium-answer prompt placeholder.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION provide a medium placeholder response.",
    choices: [],
    responseAreas: [
      {
        id: "medium-answer",
        label: "DEMO_NOT_FOR_PUBLICATION medium answer",
        responseType: "MEDIUM_TEXT",
        maxWords: 250,
      },
    ],
    scoringRubric: {
      version: 1,
      maxPoints: 1,
      scale: "NEXTGEN_POINTS",
      items: [
        {
          id: "demo-nextgen-medium-rubric",
          responseAreaId: "medium-answer",
          label: "DEMO_NOT_FOR_PUBLICATION medium-answer rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION medium"],
        },
      ],
    },
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: [],
    lawyeringSkillTopic: "nextgen.skill.02",
    masteryDimension: "DOCTRINAL",
    difficulty: "MEDIUM",
    estimatedSeconds: 240,
    setLevelTimingSeconds: 240,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-performance-task",
    subject: "NextGen Skills",
    category: "Written performance",
    examTrack: "NEXTGEN_UBE",
    format: "STANDARD_PERFORMANCE_TASK",
    stem: "DEMO_NOT_FOR_PUBLICATION performance-task prompt placeholder.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION draft a placeholder performance response.",
    choices: [],
    responseAreas: [
      {
        id: "task-response",
        label: "DEMO_NOT_FOR_PUBLICATION performance task response",
        responseType: "PERFORMANCE_TASK",
        maxWords: 600,
      },
    ],
    performanceTaskLibrary: [
      {
        id: "demo-nextgen-task-file",
        title: "DEMO_NOT_FOR_PUBLICATION task file placeholder",
        resourceType: "FILE",
        content:
          "DEMO_NOT_FOR_PUBLICATION task file and library placeholder text.",
      },
    ],
    scoringRubric: {
      version: 1,
      maxPoints: 1,
      scale: "NEXTGEN_POINTS",
      items: [
        {
          id: "demo-nextgen-task-rubric",
          responseAreaId: "task-response",
          label: "DEMO_NOT_FOR_PUBLICATION task rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION task"],
        },
      ],
    },
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: ["nextgen.skill.03"],
    lawyeringSkillTopic: "nextgen.skill.03",
    masteryDimension: "LAWYERING_SKILL",
    difficulty: "HARD",
    estimatedSeconds: 900,
    setLevelTimingSeconds: 900,
    simulationBlueprintKey: "demo-nextgen-july-2026",
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "DRAFT",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
  {
    id: "demo-nextgen-legal-research-task",
    subject: "NextGen Skills",
    category: "Legal research performance",
    examTrack: "NEXTGEN_UBE",
    format: "LEGAL_RESEARCH_PERFORMANCE_TASK",
    stem: "DEMO_NOT_FOR_PUBLICATION legal-research task prompt placeholder.",
    callOfQuestion:
      "DEMO_NOT_FOR_PUBLICATION use the placeholder library to respond.",
    choices: [],
    responseAreas: [
      {
        id: "research-response",
        label: "DEMO_NOT_FOR_PUBLICATION legal research response",
        responseType: "PERFORMANCE_TASK",
        maxWords: 600,
      },
    ],
    performanceTaskLibrary: [
      {
        id: "demo-nextgen-research-library",
        title: "DEMO_NOT_FOR_PUBLICATION research library placeholder",
        resourceType: "LIBRARY",
        content:
          "DEMO_NOT_FOR_PUBLICATION legal research library placeholder text.",
      },
    ],
    scoringRubric: {
      version: 1,
      maxPoints: 1,
      scale: "NEXTGEN_POINTS",
      items: [
        {
          id: "demo-nextgen-research-rubric",
          responseAreaId: "research-response",
          label: "DEMO_NOT_FOR_PUBLICATION legal-research rubric item",
          maxPoints: 1,
          acceptedResponseMarkers: ["DEMO_NOT_FOR_PUBLICATION research"],
        },
      ],
    },
    primaryTopic: "nextgen.doctrine.demo",
    secondaryTopics: ["nextgen.skill.04"],
    lawyeringSkillTopic: "nextgen.skill.04",
    masteryDimension: "LAWYERING_SKILL",
    difficulty: "HARD",
    estimatedSeconds: 900,
    setLevelTimingSeconds: 900,
    simulationBlueprintKey: "demo-nextgen-july-2026",
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    authorId: "demo-editor",
    reviewerId: "demo-reviewer",
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "DRAFT",
    version: 1,
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    lastReviewedAt: new Date("2026-06-24T00:00:00.000Z"),
  },
];

export const demoEssays: DemoEssayVersion[] = [
  {
    id: "demo-essay-1",
    title: "DEMO_NOT_FOR_PUBLICATION essay placeholder",
    subject: "Contracts",
    topic: "Formation",
    issue: "DEMO_NOT_FOR_PUBLICATION placeholder issue",
    sourceYear: 2026,
    difficulty: "MEDIUM",
    examTrack: "LEGACY_UBE",
    prompt:
      "DEMO_NOT_FOR_PUBLICATION essay prompt. This is workflow-only demonstration text and is not legal content.",
    callsOfQuestion: [
      "DEMO_NOT_FOR_PUBLICATION call one.",
      "DEMO_NOT_FOR_PUBLICATION call two.",
    ],
    sampleAnswer:
      "DEMO_NOT_FOR_PUBLICATION sample answer placeholder. This text is released only after submission.",
    mode: "FULL_ANSWER",
    baseTimerMinutes: 30,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    version: 1,
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "PUBLISHED",
    rubricItems: [
      {
        id: "demo-essay-1-rubric-formation",
        label: "DEMO_NOT_FOR_PUBLICATION Issue checklist item",
        description: "DEMO_NOT_FOR_PUBLICATION identify the placeholder issue.",
        maxPoints: 2,
        taxonomyNodeId: "mbe.category.contracts.formation",
        topic: "Formation",
        ruleStatement: "DEMO_NOT_FOR_PUBLICATION rule statement placeholder.",
        factApplicationGuidance:
          "DEMO_NOT_FOR_PUBLICATION fact-application guidance placeholder.",
        commonMistakes: [
          "DEMO_NOT_FOR_PUBLICATION common mistake placeholder.",
        ],
      },
      {
        id: "demo-essay-1-rubric-remedies",
        label: "DEMO_NOT_FOR_PUBLICATION Second checklist item",
        description:
          "DEMO_NOT_FOR_PUBLICATION address a second placeholder point.",
        maxPoints: 3,
        taxonomyNodeId: "mbe.category.contracts.remedies",
        topic: "Remedies",
        ruleStatement:
          "DEMO_NOT_FOR_PUBLICATION second rule statement placeholder.",
        factApplicationGuidance:
          "DEMO_NOT_FOR_PUBLICATION second fact-application guidance placeholder.",
        commonMistakes: [
          "DEMO_NOT_FOR_PUBLICATION second common mistake placeholder.",
        ],
      },
    ],
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
  },
  {
    id: "demo-essay-missing-rubric",
    title: "DEMO_NOT_FOR_PUBLICATION essay missing rubric",
    subject: "Contracts",
    topic: "Formation",
    issue: "DEMO_NOT_FOR_PUBLICATION missing rubric issue",
    sourceYear: 2026,
    difficulty: "EASY",
    examTrack: "LEGACY_UBE",
    prompt:
      "DEMO_NOT_FOR_PUBLICATION draft essay prompt without rubric for coverage reporting.",
    callsOfQuestion: ["DEMO_NOT_FOR_PUBLICATION draft call."],
    sampleAnswer: "DEMO_NOT_FOR_PUBLICATION draft sample placeholder.",
    mode: "OUTLINE_ONLY",
    baseTimerMinutes: 15,
    licenseKey: "demo-internal-license",
    sourceKey: "demo-source",
    version: 1,
    effectiveFrom: new Date("2026-06-24T00:00:00.000Z"),
    status: "DRAFT",
    rubricItems: [],
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
  },
];

export const demoPodcasts: DemoPodcastEpisode[] = [
  {
    id: "demo-podcast-1",
    title: "DEMO_NOT_FOR_PUBLICATION podcast metadata",
    status: "DRAFT",
    licenseKey: "demo-internal-license",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
  },
];

export const demoReports: DemoContentReport[] = [
  {
    id: "demo-report-1",
    contentKind: "QUESTION",
    reason: "DEMO_NOT_FOR_PUBLICATION report reason",
    status: "OPEN",
    createdAt: new Date("2026-06-24T00:00:00.000Z"),
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
  },
];
