import { demoEssays, demoQuestions } from "./demo-admin-content";
import type { PodcastLibraryEpisode } from "./podcast-library";

export const demoPodcastLibrary: PodcastLibraryEpisode[] = [
  {
    id: "demo-podcast-ready-1",
    key: "demo-podcast-ready-1",
    title: "DEMO_NOT_FOR_PUBLICATION audio orientation",
    description: "DEMO_NOT_FOR_PUBLICATION podcast fixture metadata only.",
    transcriptText:
      "DEMO_NOT_FOR_PUBLICATION transcript text for search and highlighting.",
    transcriptUri: null,
    audioUri: null,
    status: "PUBLISHED",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    effectiveFrom: "2026-06-24",
    effectiveTo: null,
    lastReviewedAt: "2026-06-24",
    sourceKey: "demo-source",
    licenseKey: "demo-internal-license",
    subject: "Civil Procedure",
    topics: ["Jurisdiction and venue"],
    summary: "Demo-only audio metadata for accessibility and player flows.",
    instructor: "Development Instructor",
    learningObjectives: [
      "DEMO_NOT_FOR_PUBLICATION identify where audio progress is saved.",
      "DEMO_NOT_FOR_PUBLICATION review synchronized transcript behavior.",
    ],
    transcriptSegments: [
      {
        id: "demo-podcast-ready-1-segment-1",
        startSeconds: 0,
        endSeconds: 20,
        text: "DEMO_NOT_FOR_PUBLICATION welcome to the audio study flow.",
      },
      {
        id: "demo-podcast-ready-1-segment-2",
        startSeconds: 20,
        endSeconds: 55,
        text: "DEMO_NOT_FOR_PUBLICATION transcript search can find this segment.",
      },
      {
        id: "demo-podcast-ready-1-segment-3",
        startSeconds: 55,
        endSeconds: 90,
        text: "DEMO_NOT_FOR_PUBLICATION bookmarks and notes attach to timestamps.",
      },
    ],
    chapters: [
      {
        id: "demo-podcast-ready-1-chapter-1",
        title: "Orientation",
        startSeconds: 0,
      },
      {
        id: "demo-podcast-ready-1-chapter-2",
        title: "Transcript tools",
        startSeconds: 20,
      },
    ],
    relatedQuestions: demoQuestions.slice(0, 1),
    relatedEssays: demoEssays.slice(0, 1),
    durationSeconds: 90,
    audioObjectKey: "demo/demo-podcast-ready-1.mp3",
  },
  {
    id: "user-podcast-torts",
    key: "user-podcast-torts",
    title: "Torts",
    description:
      "User-provided Torts audio for local study. Transcript and public-review metadata have not been added.",
    transcriptText: null,
    transcriptUri: null,
    audioUri: null,
    status: "PUBLISHED",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    effectiveFrom: "2026-06-24",
    effectiveTo: null,
    lastReviewedAt: null,
    sourceKey: "user-supplied-local",
    licenseKey: "demo-internal-license",
    subject: "Torts",
    topics: ["Torts"],
    summary:
      "User-provided Torts audio. Transcript and public-review metadata are pending.",
    instructor: "User-provided",
    learningObjectives: ["Listen to the user-provided Torts audio."],
    transcriptSegments: [],
    chapters: [
      {
        id: "user-podcast-torts-chapter-1",
        title: "Torts audio",
        startSeconds: 0,
      },
    ],
    relatedQuestions: [],
    relatedEssays: [],
    durationSeconds: 4107,
    audioObjectKey: "user-supplied/torts.mp3",
  },
  {
    id: "user-podcast-real-property",
    key: "user-podcast-real-property",
    title: "Real Property",
    description:
      "User-provided Real Property audio for local study. Transcript and public-review metadata have not been added.",
    transcriptText: null,
    transcriptUri: null,
    audioUri: null,
    status: "PUBLISHED",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    effectiveFrom: "2026-06-24",
    effectiveTo: null,
    lastReviewedAt: null,
    sourceKey: "user-supplied-local",
    licenseKey: "demo-internal-license",
    subject: "Real Property",
    topics: ["Real Property"],
    summary:
      "User-provided Real Property audio. Transcript and public-review metadata are pending.",
    instructor: "User-provided",
    learningObjectives: ["Listen to the user-provided Real Property audio."],
    transcriptSegments: [],
    chapters: [
      {
        id: "user-podcast-real-property-chapter-1",
        title: "Real Property audio",
        startSeconds: 0,
      },
    ],
    relatedQuestions: [],
    relatedEssays: [],
    durationSeconds: 3812,
    audioObjectKey: "user-supplied/real-property.mp3",
  },
  {
    id: "user-podcast-contracts",
    key: "user-podcast-contracts",
    title: "Contracts",
    description:
      "User-provided Contracts audio for local study. Transcript and public-review metadata have not been added.",
    transcriptText: null,
    transcriptUri: null,
    audioUri: null,
    status: "PUBLISHED",
    dataClassification: "DEMO_NOT_FOR_PUBLICATION",
    effectiveFrom: "2026-06-24",
    effectiveTo: null,
    lastReviewedAt: null,
    sourceKey: "user-supplied-local",
    licenseKey: "demo-internal-license",
    subject: "Contracts",
    topics: ["Contracts"],
    summary:
      "User-provided Contracts audio. Transcript and public-review metadata are pending.",
    instructor: "User-provided",
    learningObjectives: ["Listen to the user-provided Contracts audio."],
    transcriptSegments: [],
    chapters: [
      {
        id: "user-podcast-contracts-chapter-1",
        title: "Contracts audio",
        startSeconds: 0,
      },
    ],
    relatedQuestions: [],
    relatedEssays: [],
    durationSeconds: 3335,
    audioObjectKey: "user-supplied/contracts.mp3",
  },
];
